applicationName: "inventory"
deployment:
  annotations:
  podLabels:
    app: inventory
  volumes: {}
  image:
    repository: stakater/stakater-nordmart-inventory
    tag: v0.0.3
  env:
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
  - name: POSTGRESQL_HOST
    value: "stakater-nordmart-inventory-postgresql-svc"
  - name: DB_NAME
    value: "inventory"
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: inventory-postgresql-secret
        key: POSTGRES_PASSWORD
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 15
      httpGet:
        path: /actuator/health
        port: 8080
service:
  ports:
  - port: 8080
    name: https
    targetPort: 8080
rbac:
  create: true
  serviceAccount:
    create: true
configMap:
  enabled: false
secret:
   enabled: false